export * from "@/_page-configs/degrees"
export * from "@/_page-configs/ranks"
export * from "@/_page-configs/positions"
export * from "@/_page-configs/scientific_directions"
export * from "@/_page-configs/roles"
export * from "@/_page-configs/users"
export * from "@/_page-configs/projects"
export * from "@/_page-configs/contests_admin"